### ISSUE TITLE
ConSinGAN instead of SinGAN?

### ISSUE THREAD

**Issue by eps696** [rmokady/structural-analogy#1]
hello,
did you consider using [ConSinGAN](https://github.com/tohinz/ConSinGAN) instead of SinGAN? 
on my practice it proved to be way more optimized (less memory-hungry), easier to explore and producing better results (more consistent and visually pleasing).

**Comment by rmokady** [comment]
We didn't use ConSinGAN.
I agree that it would be interesting to see if we can get better results using ConSinGAN.
