### ISSUE TITLE
paths when resuming from checkpoint 

### ISSUE THREAD

**Issue by markhanslip** [rmokady/structural-analogy#2]
Hi, this model is fantastic, thanks so much! 

In order to resume training from a checkpoint, which netG and netD should be specified in the call to train.py? Is unclear to me since there are .pth files for G and D corresponding to each image. Do args --netG and --netD accept more than one path each?  

Best wishes,

Mark

**Comment by rmokady** [comment]
Hi,
Currently, train.py don't really supports resume of the training.
I will fix it soon, stay tuned.

**Comment by markhanslip** [comment]
thanks for the quick response. it would be a great feature!

**Comment by rmokady** [comment]
Hi @markhanslip,
I fix it.

You can now use 
`--load checkpoint_folder`
