### ISSUE TITLE
how to reduce the memory usage at train_video ?

### ISSUE THREAD

**Issue by andorxornot** [rmokady/structural-analogy#3]
i'm trying to test train for video on 11gb 1080ti and get a "out of memory" error (at 5-6 scale).
also train works perfect for image

**Comment by rmokady** [comment]
Hi @andorxornot ,
Thanks for your interest in our work

Did you try to train on our volcano video?
If not, could you check how many frames your video contains?
If it is a long video you can try to work on a shorter version for start

**Comment by andorxornot** [comment]
yeah, i used "Video Translation" commands from readme. also i had to make some little fixes because i'm testing for windows.

**Comment by rmokady** [comment]
Hi @andorxornot,
I found one issue at the quant_video command regarding the conversion to greyscale
But, I wasn't able to reproduce your issue
I used GeForce GTX 1080 Ti, and didn't encounter any "out of memory issue"

Maybe this issue related to Windows? I would check that at the end of each scale the weights memory is freed successfully

**Comment by andorxornot** [comment]
maybe the widows use more memory initially. i have only 8-9gb free on start

**Comment by rmokady** [comment]
Maybe you can try a smaller image size? e.g. 192X192 or 160X160.
