### ISSUE TITLE
Day to Infrared conversion

### ISSUE THREAD

**Issue by trathpai** [rmokady/structural-analogy#4]
Kudos for the great work.. However i am not getting desired result for day to infrared conversion? Do you have any recommendations what might help?

**Comment by rmokady** [comment]
Hi,
I didn't tried our method over day to infrared, so I can't tell exactly why the results are no good
Can you provide the image and the result?

**Comment by trathpai** [comment]
Hi,

You can find the images here:
[https://imgur.com/a/A789jsx]

**Comment by trathpai** [comment]
Hi ,

Please find the images here:
[day2ir](https://imgur.com/a/A789jsx)

**Comment by rmokady** [comment]
I would try to use the "sketch to image" parameters where the sketch is the IR
